name: ci-diagnose
on:
  push:
    branches: ['automation/**', 'automated/**']
  workflow_dispatch: {}
jobs:
  diag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Collect context
        run: |
          set -euo pipefail
          mkdir -p diagnostics
          echo "repo=${GITHUB_REPOSITORY}" > diagnostics/diag.txt
          echo "ref=${GITHUB_REF}" >> diagnostics/diag.txt
          echo "sha=${GITHUB_SHA}" >> diagnostics/diag.txt
          echo "actor=${GITHUB_ACTOR}" >> diagnostics/diag.txt
          echo "event=${GITHUB_EVENT_NAME}" >> diagnostics/diag.txt
      - name: Default branch and last runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsSL -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}" | jq -r '.default_branch' > diagnostics/default_branch.txt
          curl -fsSL -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=10" > diagnostics/last_runs.json
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-${{ github.run_id }}
          path: diagnostics/*
      - name: Commit diagnostics branch
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TS="$(date -u +%Y%m%d_%H%M%S)"
          git config user.name "scan-bot"
          git config user.email "scan-bot@users.noreply.github.com"
          git checkout -B ci-diagnostics
          REPORTS_DIR="diagnostics/$TS"
          mkdir -p "$REPORTS_DIR"
          mv diagnostics/* "$REPORTS_DIR/" || true
          git add diagnostics || true
          git commit -m "ci: diagnostics $TS" || true
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin ci-diagnostics
