name: ci-diagnose
on:
  push:
    branches: ['automation/**', 'automated/**']
  workflow_dispatch: {}
jobs:
  diag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install jq
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq curl
      - name: Collect diagnostics
        run: |
          set -euo pipefail
          mkdir -p diagnostics
          echo "repo=${GITHUB_REPOSITORY}" > diagnostics/diag.txt
          echo "ref=${GITHUB_REF}" >> diagnostics/diag.txt
          echo "sha=${GITHUB_SHA}" >> diagnostics/diag.txt
          echo "actor=${GITHUB_ACTOR}" >> diagnostics/diag.txt
          echo "event=${GITHUB_EVENT_NAME}" >> diagnostics/diag.txt
          curl -fsSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}" | jq -r '.default_branch' > diagnostics/default_branch.txt
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-${{ github.run_id }}
          path: diagnostics/*
