name: Jules - Full Security Scan

on:
  workflow_dispatch:
    inputs:
      target:
        description: "What to scan: repo | docker | iac"
        required: false
        default: repo
      sev:
        description: "Minimum severity: low | medium | high | critical"
        required: false
        default: medium
  push:
    branches:
      - "**"           # Run on any branch (change if you only want main)
  pull_request:
    branches:
      - main           # Run on PRs targeting main

# Permissions needed to upload Code Scanning reports (SARIF)
permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: full-scan-${{ github.ref }}
  cancel-in-progress: true

# Safe defaults for inputs to prevent skipping on non-interactive events
env:
  TARGET: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.target) || 'repo' }}
  MIN_SEV: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.sev) || 'medium' }}

  # Convert severity to the format Trivy expects
  # low -> LOW,MEDIUM,HIGH,CRITICAL
  # medium -> MEDIUM,HIGH,CRITICAL
  # high -> HIGH,CRITICAL
  # critical -> CRITICAL
  TRIVY_SEVERITY: ${{ fromJSON('{
      "low":"LOW,MEDIUM,HIGH,CRITICAL",
      "medium":"MEDIUM,HIGH,CRITICAL",
      "high":"HIGH,CRITICAL",
      "critical":"CRITICAL"
    }')[((github.event_name == 'workflow_dispatch' && github.event.inputs.sev) || 'medium')] }}

jobs:
  scan:
    # Optional: skip run if commit message contains [skip ci]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug event (useful when "No jobs were run")
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "base_ref=${{ github.base_ref }}"
          echo "TARGET=$TARGET"
          echo "MIN_SEV=$MIN_SEV"
          echo "TRIVY_SEVERITY=$TRIVY_SEVERITY"

      - name: Checkout
        uses: actions/checkout@v4

      # ===== Example of a real scanner: Trivy repo scan + SARIF upload =====
      - name: Run Trivy (filesystem / repo scan)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          severity: ${{ env.TRIVY_SEVERITY }}
          ignore-unfixed: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # ===== Example of expanding based on TARGET =====
      - name: Conditional Docker scan
        if: ${{ env.TARGET == 'docker' }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ github.repository }}:latest
          format: sarif
          output: trivy-image.sarif
          severity: ${{ env.TRIVY_SEVERITY }}

      - name: Upload Docker SARIF
        if: ${{ env.TARGET == 'docker' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
